### ISSUE TITLE
Improve documentation of raw subqueries

### ISSUE THREAD

**Issue by aduh95** [Twipped/QueryizeJS#21]
Hello,

I am trying to append data to a JSON array in my database using [MariaDB JSON functions](https://mariadb.com/kb/en/library/json_array_append/) :

```sql
UPDATE table SET jsonArray = JSON_ARRAY_APPEND(jsonArray, '$', ?) WHERE ID = 1;
```
How can I safely pass a user input to queryize like this? It seems the subqueries thing is not very much documented (I searched for `raw` in the web page, and all I could find was code examples and changelog entries). I wish I could do something like that:

```js
const data = `some user input`;
queryize()
  .table("table")
  .update()
  .set("jsonArray", { raw: "JSON_ARRAY_APPEND(jsonArray, '$', ?)", data });

```

Does queryize provide something like that? If not, is it possible to add this feature?

**Comment by Twipped** [comment]
The best way to do this is to use the [insertBinding](http://queryizejs.com/#methodqueryinsertBinding) function to define a custom named placeholder.

```js
queryize()
  .table("table")
  .update()
  .insertBinding('myData', data)
  .set("jsonArray", { raw: "JSON_ARRAY_APPEND(jsonArray, '$', {{myData}})" });
```
