### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jedmao** [Twipped/QueryizeJS#25]
Any interest in supporting TypeScript?

**Comment by Twipped** [comment]
I don't use it myself. If somebody wants to submit a PR for support I can merge it, but I'm not likely to keep it updated.

**Comment by jedmao** [comment]
Would you be open to the source code being converted into TypeScript? This is the most ideal way to support TypeScript, as the type definitions would be generated and always in sync with the source.

**Comment by Twipped** [comment]
I mean, if you want to fork it and release it as queryize-ts or something, go right ahead, but I have no interest in maintaining TS code myself.
